[package]
edition = "2021"
name = "hmny"
version = "0.0.1-dev"

[dependencies]
polywrap = "0.1.9"
serde = {version = "1.0", features = ["derive"]}

[profile.release]
lto = true
opt-level = "s"
panic = 'abort'
